#include "macros.hpp"

class XtdGearInfos
{
    class CfgWeapons
    {
        // ===================================================================================================================================
        // UNIFORMS
        // ===================================================================================================================================

        // --- US Army BDU ---
        DEFINE_U_BDU(U_simc_bdu_erla_blench,"US Army","M81","Standard","Full","No","No","No")
        DEFINE_U_BDU(U_Simc_bdu_erla_blench_trop,"US Army","M81","Standard","Rolled","No","No","No")
        DEFINE_U_BDU(U_Simc_bdu_erla_blench_nomex,"US Army","M81","Standard","Full","No","Yes","No")
        DEFINE_U_BDU(U_simc_bdu_erla_gas_blench,"US Army","M81","Standard","Full","Yes","No","No")
        DEFINE_U_BDU(U_simc_bdu_erla_gas_blench_trop,"US Army","M81","Standard","Rolled","Yes","No","No")
        DEFINE_U_BDU(U_simc_bdu_erla_gas_blench_nomex,"US Army","M81","Standard","Full","Yes","Yes","No")
        DEFINE_U_BDU(U_simc_bdu_erla_blench_desu,"US Army","DCU-6","Standard","Full","No","No","No")
        DEFINE_U_BDU(U_simc_bdu_erla_blench_desu_trop,"US Army","DCU-6","Standard","Rolled","No","No","No")
        DEFINE_U_BDU(U_simc_bdu_erla_blench_desu_nomex,"US Army","DCU-6","Standard","Full","No","Yes","No")
        DEFINE_U_BDU(U_simc_bdu_erla_gas_blench_desu,"US Army","DCU-6","Standard","Full","Yes","No","No")
        DEFINE_U_BDU(U_simc_bdu_erla_gas_blench_desu_trop,"US Army","DCU-6","Standard","Rolled","Yes","No","No")
        DEFINE_U_BDU(U_simc_bdu_erla_gas_blench_desu_nomex,"US Army","DCU-6","Standard","Full","Yes","Yes","No")
        DEFINE_U_BDU(U_simc_bdu_laat,"US Army","M81","Standard","Full","No","No","No")
        DEFINE_U_BDU(U_Simc_bdu_laat_trop,"US Army","M81","Standard","Rolled","No","No","No")
        DEFINE_U_BDU(U_simc_bdu_laat_knee,"US Army","M81","Standard","Full","No","No","Yes")
        DEFINE_U_BDU(U_simc_bdu_laat_knee_trop,"US Army","M81","Standard","Rolled","No","No","Yes")
        DEFINE_U_BDU(U_Simc_bdu_laat_nomex,"US Army","M81","Standard","Full","No","Yes","No")
        DEFINE_U_BDU(U_simc_bdu_laat_nomex_knee,"US Army","M81","Standard","Full","No","Yes","Yes")
        DEFINE_U_BDU(U_simc_bdu_laat_knee_nomex_trop,"US Army","M81","Standard","Rolled","No","Yes","Yes")
        DEFINE_U_BDU(U_Simc_bdu_laat_gas,"US Army","M81","Standard","Full","Yes","No","No")
        DEFINE_U_BDU(U_Simc_bdu_laat_gas_trop,"US Army","M81","Standard","Rolled","Yes","No","No")
        DEFINE_U_BDU(U_Simc_bdu_laat_gas_nomex,"US Army","M81","Standard","Full","Yes","Yes","No")
        DEFINE_U_BDU(U_simc_bdu_laat_gas_knee,"US Army","M81","Standard","Full","Yes","No","Yes")
        DEFINE_U_BDU(U_simc_bdu_laat_gas_knee_trop,"US Army","M81","Standard","Rolled","Yes","No","Yes")
        DEFINE_U_BDU(U_simc_bdu_laat_gas_knee_nomex,"US Army","M81","Standard","Full","Yes","Yes","Yes")
        DEFINE_U_BDU(U_simc_bdu_laat_gas_knee_nomex_trop,"US Army","M81","Standard","Rolled","Yes","Yes","Yes")
        DEFINE_U_BDU(U_Simc_bdu_laat_desu,"US Army","DCU-6","Standard","Full","No","No","No")
        DEFINE_U_BDU(U_Simc_bdu_laat_desu_trop,"US Army","DCU-6","Standard","Rolled","No","No","No")
        DEFINE_U_BDU(U_Simc_bdu_laat_desu_nomex,"US Army","DCU-6","Standard","Full","No","Yes","No")
        DEFINE_U_BDU(U_simc_bdu_laat_desu_knee,"US Army","DCU-6","Standard","Full","No","No","Yes")
        DEFINE_U_BDU(U_simc_bdu_laat_desu_knee_trop,"US Army","DCU-6","Standard","Rolled","No","No","Yes")
        DEFINE_U_BDU(U_simc_bdu_laat_desu_nomex_knee,"US Army","DCU-6","Standard","Full","No","Yes","Yes")
        DEFINE_U_BDU(U_simc_bdu_laat_desu_knee_nomex_trop,"US Army","DCU-6","Standard","Rolled","No","Yes","Yes")
        DEFINE_U_BDU(U_simc_bdu_laat_desu_gas,"US Army","DCU-6","Standard","Full","Yes","No","No")
        DEFINE_U_BDU(U_simc_bdu_laat_desu_gas_trop,"US Army","DCU-6","Standard","Rolled","Yes","No","No")
        DEFINE_U_BDU(U_simc_bdu_laat_desu_gas_nomex,"US Army","DCU-6","Standard","Full","Yes","Yes","No")
        DEFINE_U_BDU(U_simc_bdu_laat_desu_gas_knee,"US Army","DCU-6","Standard","Full","Yes","No","Yes")
        DEFINE_U_BDU(U_simc_bdu_laat_desu_gas_knee_trop,"US Army","DCU-6","Standard","Rolled","Yes","No","Yes")
        DEFINE_U_BDU(U_simc_bdu_laat_desu_gas_knee_nomex,"US Army","DCU-6","Standard","Full","Yes","Yes","Yes")
        DEFINE_U_BDU(U_simc_bdu_laat_desu_gas_knee_nomex_trop,"US Army","DCU-6","Standard","Rolled","Yes","Yes","Yes")
        DEFINE_U_BDU(U_Simc_DCU,"US Army","DCU-3","Standard","Full","No","No","No")
        DEFINE_U_BDU(U_Simc_DCU_trop,"US Army","DCU-3","Standard","Rolled","No","No","No")
        DEFINE_U_BDU(U_Simc_DCU_nomex,"US Army","DCU-3","Standard","Full","No","Yes","No")
        DEFINE_U_BDU(U_Simc_DCU_knee,"US Army","DCU-3","Standard","Full","No","No","Yes")
        DEFINE_U_BDU(U_Simc_DCU_knee_trop,"US Army","DCU-3","Standard","Rolled","No","No","Yes")
        DEFINE_U_BDU(U_Simc_DCU_nomex_knee,"US Army","DCU-3","Standard","Full","No","Yes","Yes")
        DEFINE_U_BDU(U_Simc_DCU_knee_nomex_trop,"US Army","DCU-3","Standard","Rolled","No","Yes","Yes")
        DEFINE_U_BDU(U_simc_DCU_gas,"US Army","DCU-3","Standard","Full","Yes","No","No")
        DEFINE_U_BDU(U_simc_DCU_gas_trop,"US Army","DCU-3","Standard","Rolled","Yes","No","No")
        DEFINE_U_BDU(U_simc_DCU_gas_nomex,"US Army","DCU-3","Standard","Full","Yes","Yes","No")
        DEFINE_U_BDU(U_simc_DCU_gas_knee,"US Army","DCU-3","Standard","Full","Yes","No","Yes")
        DEFINE_U_BDU(U_simc_DCU_gas_knee_trop,"US Army","DCU-3","Standard","Rolled","Yes","No","Yes")
        DEFINE_U_BDU(U_simc_DCU_gas_knee_nomex,"US Army","DCU-3","Standard","Full","Yes","Yes","Yes")
        DEFINE_U_BDU(U_simc_DCU_gas_knee_nomex_trop,"US Army","DCU-3","Standard","Rolled","Yes","Yes","Yes")
        DEFINE_U_BDU(U_simc_bdu_raid,"US Army","M81","RAID","Full","No","No","No")
        DEFINE_U_BDU(U_Simc_bdu_raid_trop,"US Army","M81","RAID","Rolled","No","No","No")
        DEFINE_U_BDU(U_simc_bdu_raid_knee,"US Army","M81","RAID","Full","No","No","Yes")
        DEFINE_U_BDU(U_simc_bdu_raid_knee_trop,"US Army","M81","RAID","Rolled","No","No","Yes")
        DEFINE_U_BDU(U_Simc_bdu_raid_nomex,"US Army","M81","RAID","Full","No","Yes","No")
        DEFINE_U_BDU(U_simc_bdu_raid_nomex_knee,"US Army","M81","RAID","Full","No","Yes","Yes")
        DEFINE_U_BDU(U_simc_bdu_raid_knee_nomex_trop,"US Army","M81","RAID","Rolled","No","Yes","Yes")
        DEFINE_U_BDU(U_simc_DCU_raid,"US Army","DCU-3","RAID","Full","No","No","No")
        DEFINE_U_BDU(U_simc_DCU_raid_trop,"US Army","DCU-3","RAID","Rolled","No","No","No")
        DEFINE_U_BDU(U_simc_DCU_raid_knee,"US Army","DCU-3","RAID","Full","No","No","Yes")
        DEFINE_U_BDU(U_simc_DCU_raid_knee_trop,"US Army","DCU-3","RAID","Rolled","No","No","Yes")
        DEFINE_U_BDU(U_simc_DCU_raid_nomex,"US Army","DCU-3","RAID","Full","No","Yes","No")
        DEFINE_U_BDU(U_simc_DCU_raid_nomex_knee,"US Army","DCU-3","RAID","Full","No","Yes","Yes")
        DEFINE_U_BDU(U_simc_DCU_raid_knee_nomex_trop,"US Army","DCU-3","RAID","Rolled","No","Yes","Yes")
        DEFINE_U_BDU(U_Simc_bdu_rdf_blench_od7,"US Army","OD","Standard","Full","No","No","No")
        DEFINE_U_BDU(U_Simc_bdu_rdf_blench_od7_trop,"US Army","OD","Standard","Rolled","No","No","No")
        DEFINE_U_BDU(U_Simc_bdu_rdf_blench_erdl,"US Army","ERDL-H","Standard","Full","No","No","No")
        DEFINE_U_BDU(U_Simc_bdu_rdf_blench_erdl_trop,"US Army","ERDL-H","Standard","Rolled","No","No","No")
        DEFINE_U_BDU(U_simc_bdu_blench_mout,"US Army","T/MOUT","Standard","Full","No","No","No")
        DEFINE_U_BDU(U_simc_bdu_blench_mout_trop,"US Army","T/MOUT","Standard","Rolled","No","No","No")
        DEFINE_U_BDU(U_simc_bdu_blench_mout_knee,"US Army","T/MOUT","Standard","Full","No","No","Yes")
        DEFINE_U_BDU(U_simc_bdu_blench_mout_knee_trop,"US Army","T/MOUT","Standard","Rolled","No","No","Yes")
        DEFINE_U_BDU(U_simc_bdu_blench_mout_nomex,"US Army","T/MOUT","Standard","Full","No","Yes","No")
        DEFINE_U_BDU(U_simc_bdu_blench_mout_knee_nomex,"US Army","T/MOUT","Standard","Full","No","Yes","Yes")
        DEFINE_U_BDU(U_simc_bdu_blench_mout_knee_nomex_trop,"US Army","T/MOUT","Standard","Rolled","No","Yes","Yes")

        // --- USMC BDU ---
        DEFINE_U_BDU(U_simc_bdu_rdf_MC,"USMC","ERDL-L","Standard","Full","No","No","No")
        DEFINE_U_BDU(U_simc_bdu_rdf_MC_trop,"USMC","ERDL-L","Standard","Rolled","No","No","No")
        DEFINE_U_BDU(U_simc_bdu_rdf_MC_tee,"USMC","ERDL-L","Tee","Rolled","No","No","No")
        DEFINE_U_BDU(U_simc_bdu_rdf_MC_erdl,"USMC","ERDL-H","Standard","Full","No","No","No")
        DEFINE_U_BDU(U_simc_bdu_rdf_MC_erdl_trop,"USMC","ERDL-H","Standard","Rolled","No","No","No")
        DEFINE_U_BDU(U_simc_bdu_rdf_MC_erdl_tee,"USMC","ERDL-H","Tee","Rolled","No","No","No")
        DEFINE_U_BDU(U_simc_bdu_rdf_MC_desu,"USMC","DCU-6","Standard","Full","No","No","No")
        DEFINE_U_BDU(U_simc_bdu_rdf_MC_desu_trop,"USMC","DCU-6","Standard","Rolled","No","No","No")
        DEFINE_U_BDU(U_simc_bdu_rdf_MC_desu_tee,"USMC","DCU-6","Tee","Rolled","No","No","No")
        DEFINE_U_BDU(U_simc_bdu_rdf_MC_gas,"USMC","ERDL-L","Standard","Full","Yes","No","No")
        DEFINE_U_BDU(U_simc_bdu_rdf_MC_gas_trop,"USMC","ERDL-L","Standard","Rolled","Yes","No","No")
        DEFINE_U_BDU(U_simc_bdu_rdf_MC_gas_erdl,"USMC","ERDL-H","Standard","Full","Yes","No","No")
        DEFINE_U_BDU(U_simc_bdu_rdf_MC_gas_erdl_trop,"USMC","ERDL-H","Standard","Rolled","Yes","No","No")
        DEFINE_U_BDU(U_simc_bdu_rdf_MC_gas_desu,"USMC","DCU-6","Standard","Full","Yes","No","No")
        DEFINE_U_BDU(U_simc_bdu_rdf_MC_gas_desu_trop,"USMC","DCU-6","Standard","Rolled","Yes","No","No")
        DEFINE_U_BDU(U_Simc_bdu_erla_MC,"USMC","M81","Standard","Full","No","No","No")
        DEFINE_U_BDU(U_Simc_bdu_erla_MC_trop,"USMC","M81","Standard","Rolled","No","No","No")
        DEFINE_U_BDU(U_Simc_bdu_erla_MC_tee,"USMC","M81","Tee","Rolled","No","No","No")
        DEFINE_U_BDU(U_Simc_bdu_erla_MC_nomex,"USMC","M81","Standard","Full","No","Yes","No")
        DEFINE_U_BDU(U_simc_bdu_erla_MC_gas,"USMC","M81","Standard","Full","Yes","No","No")
        DEFINE_U_BDU(U_simc_bdu_erla_MC_gas_trop,"USMC","M81","Standard","Rolled","Yes","No","No")
        DEFINE_U_BDU(U_simc_bdu_erla_MC_gas_nomex,"USMC","M81","Standard","Full","Yes","Yes","No")
        DEFINE_U_BDU(U_Simc_bdu_erla_MC_desu,"USMC","DCU-3","Standard","Full","No","No","No")
        DEFINE_U_BDU(U_Simc_bdu_erla_MC_desu_trop,"USMC","DCU-3","Standard","Rolled","No","No","No")
        DEFINE_U_BDU(U_Simc_bdu_erla_MC_desu_tee,"USMC","DCU-3","Tee","Rolled","No","No","No")
        DEFINE_U_BDU(U_Simc_bdu_erla_MC_desu_nomex,"USMC","DCU-3","Standard","Full","No","Yes","No")
        DEFINE_U_BDU(U_simc_bdu_erla_MC_mout,"USMC","T/MOUT","Standard","Full","No","No","No")
        DEFINE_U_BDU(U_simc_bdu_erla_MC_mout_trop,"USMC","T/MOUT","Standard","Rolled","No","No","No")
        DEFINE_U_BDU(U_Simc_bdu_erla_MC_mout_nomex,"USMC","T/MOUT","Standard","Full","No","Yes","No")
        DEFINE_U_BDU(U_simc_bdu_eto_mc_mout,"USMC","T/MOUT","Standard","Full","No","No","No")
        DEFINE_U_BDU(U_simc_bdu_eto_mc_mout_trop,"USMC","T/MOUT","Standard","Rolled","No","No","No")
        DEFINE_U_BDU(U_Simc_bdu_eto_MC_mout_knee,"USMC","T/MOUT","Standard","Full","No","No","Yes")
        DEFINE_U_BDU(U_simc_bdu_eto_mc_mout_knee_trop,"USMC","T/MOUT","Standard","Rolled","No","No","Yes")
        DEFINE_U_BDU(U_Simc_bdu_eto_MC_mout_nomex,"USMC","T/MOUT","Standard","Full","No","Yes","No")
        DEFINE_U_BDU(U_Simc_bdu_eto_MC_mout_knee_nomex,"USMC","T/MOUT","Standard","Full","No","Yes","Yes")
        DEFINE_U_BDU(U_Simc_bdu_eto_MC_mout_knee_nomex_trop,"USMC","T/MOUT","Standard","Rolled","No","Yes","Yes")
        DEFINE_U_BDU(U_simc_bdu_eto_gas_mc_mout,"USMC","T/MOUT","Standard","Full","Yes","No","No")
        DEFINE_U_BDU(U_simc_bdu_eto_gas_mc_mout_trop,"USMC","T/MOUT","Standard","Rolled","Yes","No","No")
        DEFINE_U_BDU(U_simc_bdu_eto_gas_mc_mout_knee,"USMC","T/MOUT","Standard","Full","Yes","No","Yes")
        DEFINE_U_BDU(U_simc_bdu_eto_gas_mc_mout_knee_trop,"USMC","T/MOUT","Standard","Rolled","Yes","No","Yes")
        DEFINE_U_BDU(U_simc_bdu_eto_gas_mc_mout_nomex,"USMC","T/MOUT","Standard","Full","Yes","Yes","No")
        DEFINE_U_BDU(U_simc_bdu_eto_gas_mc_mout_knee_nomex,"USMC","T/MOUT","Standard","Full","Yes","Yes","Yes")
        DEFINE_U_BDU(U_simc_bdu_eto_gas_mc_mout_knee_nomex_trop,"USMC","T/MOUT","Standard","Rolled","Yes","Yes","Yes")

        // --- M-65 Jacket ---
        DEFINE_U_JACKET(U_Simc_bdu_veldjas_m81,"M81","M81","No")
        DEFINE_U_JACKET(U_Simc_bdu_veldjas_m81_trop,"M81","M81","No")
        DEFINE_U_JACKET(U_Simc_bdu_veldjas_m81_gas,"M81","M81","Yes")
        DEFINE_U_JACKET(U_Simc_bdu_veldjas_m81_gas_trop,"M81","M81","Yes")
        DEFINE_U_JACKET(U_Simc_bdu_veldjas,"OD","M81","No")
        DEFINE_U_JACKET(U_Simc_bdu_veldjas_trop,"OD","M81","No")
        DEFINE_U_JACKET(U_Simc_bdu_veldjas_gas,"OD","M81","Yes")
        DEFINE_U_JACKET(U_Simc_bdu_veldjas_gas_trop,"OD","M81","Yes")
        
        // --- DNCE ---
        DEFINE_U_DNCE(U_Simc_DNCE_bdu,"M81")
        DEFINE_U_DNCE(U_Simc_DNCE_desu,"DCU-6")
        DEFINE_U_DNCE(U_Simc_DNCE_dcu,"DCU-3")

        // --- Civilian & Commando ---
        DEFINE_U_CIV(U_Simc_bdu_civ,"Khaki","BDU","Full","Untucked")
        DEFINE_U_CIV(U_simc_bdu_civ_trop,"White","BDU","Rolled","Untucked")
        DEFINE_U_CIV(U_simc_bdu_civ_surf,"Surf","BDU","Rolled","Untucked")
        DEFINE_U_CIV(U_Simc_bdu_civ_desu,"Blue-Dark","Desert","Full","Untucked")
        DEFINE_U_CIV(U_Simc_bdu_civ_desu_trop,"Green","Desert","Rolled","Untucked")
        DEFINE_U_CIV(U_Simc_bdu_civ_DT,"Red-Light","DT","Full","Untucked")
        DEFINE_U_CIV(U_Simc_bdu_civ_DT_trop,"Blue","DT","Rolled","Untucked")
        DEFINE_U_CIV(U_Simc_DCU_civ,"White","DCU","Full","Untucked")
        DEFINE_U_CIV(U_Simc_DCU_civ_trop,"Red","DCU","Rolled","Untucked")
        DEFINE_U_CDO(U_Simc_CDO_bdu,"BDU","Full","Untucked")
        DEFINE_U_CDO(U_Simc_CDO_bdu_trop,"BDU","Rolled","Untucked")
        DEFINE_U_CDO(U_Simc_CDO_bdu_trop_alt,"BDU","Rolled","Untucked")
        DEFINE_U_CDO(U_Simc_CDO_bdu_tuck,"BDU","Full","Tucked")
        DEFINE_U_CDO(U_Simc_CDO_bdu_tuck_alt,"BDU","Full","Tucked")
        DEFINE_U_CDO(U_Simc_CDO_bdu_desu,"Desert","Full","Untucked")
        DEFINE_U_CDO(U_Simc_CDO_bdu_desu_trop,"Desert","Rolled","Untucked")
        DEFINE_U_CDO(U_Simc_CDO_bdu_desu_trop_alt,"Desert","Rolled","Untucked")
        DEFINE_U_CDO(U_Simc_CDO_bdu_desu_tuck,"Desert","Full","Tucked")
        DEFINE_U_CDO(U_Simc_CDO_bdu_desu_tuck_alt,"Desert","Full","Tucked")
        DEFINE_U_CDO(U_Simc_CDO_bdu_DT,"DT","Full","Untucked")
        DEFINE_U_CDO(U_Simc_CDO_bdu_DT_trop,"DT","Rolled","Untucked")
        DEFINE_U_CDO(U_Simc_CDO_bdu_DT_trop_alt,"DT","Rolled","Untucked")
        DEFINE_U_CDO(U_Simc_CDO_bdu_DT_tuck,"DT","Full","Tucked")
        DEFINE_U_CDO(U_Simc_CDO_bdu_DT_tuck_alt,"DT","Full","Tucked")
        DEFINE_U_CDO(U_Simc_CDO_DCU,"DCU","Full","Untucked")
        DEFINE_U_CDO(U_Simc_CDO_DCU_trop,"DCU","Rolled","Untucked")
        DEFINE_U_CDO(U_Simc_CDO_DCU_trop_alt,"DCU","Rolled","Untucked")
        DEFINE_U_CDO(U_Simc_CDO_DCU_tuck,"DCU","Full","Tucked")
        DEFINE_U_CDO(U_Simc_CDO_DCU_tuck_alt,"DCU","Full","Tucked")
        DEFINE_U_CDO(U_Simc_CDO_bdu_mout,"T/MOUT","Full","Untucked")
        DEFINE_U_CDO(U_Simc_CDO_bdu_mout_trop,"T/MOUT","Rolled","Untucked")
        DEFINE_U_CDO(U_Simc_CDO_bdu_mout_trop_alt,"T/MOUT","Rolled","Untucked")
        DEFINE_U_CDO(U_Simc_CDO_bdu_mout_tuck,"T/MOUT","Full","Tucked")
        DEFINE_U_CDO(U_Simc_CDO_bdu_mout_tuck_alt,"T/MOUT","Full","Tucked")

        // ===================================================================================================================================
        // VESTS
        // ===================================================================================================================================
        
        // --- ALICE Webbing ---
        DEFINE_V_ALICE(V_Simc_Alice,"LC-1","Rifleman","None")
        DEFINE_V_ALICE(V_Simc_Alice_alt,"LC-1","Rifleman (Alt)","None")
        DEFINE_V_ALICE(V_Simc_Alice_lc2,"LC-2","Rifleman","None")
        DEFINE_V_ALICE(V_Simc_Alice_lc2_alt,"LC-2","Rifleman (Alt)","None")
        DEFINE_V_ALICE(V_Simc_Alice_M56,"LC-1","Rifleman (M56)","None")
        DEFINE_V_ALICE(V_Simc_Alice_sekop,"LC-1","Rifleman","E-Tool")
        DEFINE_V_ALICE(V_Simc_Alice_45,"LC-1","Sidearm","None")
        DEFINE_V_ALICE(V_Simc_Alice_lc2_45,"LC-2","Sidearm","None")
        DEFINE_V_ALICE(V_Simc_Alice_lc2_45_ligt,"LC-2","Light","None")
        DEFINE_V_ALICE(V_Simc_Alice_ligt,"LC-1","Light","None")
        DEFINE_V_ALICE(V_Simc_Alice_60,"LC-1","MG","None")
        DEFINE_V_ALICE(V_Simc_Alice_lc2_60,"LC-2","MG","None")
        DEFINE_V_ALICE(V_Simc_Alice_249,"LC-2","SAW","None")
        DEFINE_V_ALICE(V_Simc_nadevest_alice,"LC-1","Grenadier","None")
        
        // --- Flak Vests ---
        DEFINE_V_FLAK(V_Simc_flak_55_alice,"M1955","LC-1","Rifleman","None")
        DEFINE_V_FLAK(V_Simc_flak_55_alice_alt,"M1955","LC-1","Rifleman (Alt)","None")
        DEFINE_V_FLAK(V_Simc_flak_55_alice_m56,"M1955","LC-1","Rifleman","Rifleman (M56)")
        DEFINE_V_FLAK(V_Simc_flak_55_alice_etool,"M1955","LC-1","Rifleman","E-Tool")
        DEFINE_V_FLAK(V_Simc_flak_55_alice_45,"M1955","LC-1","Sidearm","None")
        DEFINE_V_FLAK(V_Simc_flak_55_alice_60,"M1955","LC-1","MG","None")
        DEFINE_V_FLAK(V_Simc_nadevest_mc_flak_alice,"M1955","LC-1","Grenadier","None")
        DEFINE_V_FLAK(V_Simc_flak_alice,"M69","LC-1","Rifleman","None")
        DEFINE_V_FLAK(V_Simc_flak_alice_etool,"M69","LC-1","Rifleman","E-Tool")
        DEFINE_V_FLAK(V_Simc_flak_alice_45,"M69","LC-1","Sidearm","None")
        DEFINE_V_FLAK(V_Simc_flak_alice_60,"M69","LC-1","MG","None")
        DEFINE_V_FLAK(V_Simc_nadevest_flak_alice,"M69","LC-1","Grenadier","None")

        // --- PASGT ---
        DEFINE_V_PASGT(V_Simc_vest_pasgt,"M81","None","Rifleman")
        DEFINE_V_PASGT(V_Simc_vest_pasgt_alice,"M81","ALICE","Rifleman")
        DEFINE_V_PASGT(V_Simc_vest_pasgt_alice_alt,"M81","ALICE","Rifleman (Alt)")
        DEFINE_V_PASGT(V_Simc_vest_pasgt_alice_lc2,"M81","ALICE","Rifleman")
        DEFINE_V_PASGT(V_Simc_vest_pasgt_alice_lc2_alt,"M81","ALICE","Rifleman (Alt)")
        DEFINE_V_PASGT(V_Simc_vest_pasgt_alice_m56,"M81","ALICE","Rifleman (M56)")
        DEFINE_V_PASGT(V_Simc_vest_pasgt_alice_etool,"M81","ALICE","Rifleman")
        DEFINE_V_PASGT(V_Simc_vest_pasgt_alice_45,"M81","ALICE","Sidearm")
        DEFINE_V_PASGT(V_Simc_vest_pasgt_alice_lc2_45,"M81","ALICE","Sidearm")
        DEFINE_V_PASGT(V_Simc_vest_pasgt_alice_lc2_45_ligt,"M81","ALICE","Light")
        DEFINE_V_PASGT(V_Simc_vest_pasgt_alice_45_ligt,"M81","ALICE","Light")
        DEFINE_V_PASGT(V_Simc_vest_pasgt_alice_60,"M81","ALICE","MG")
        DEFINE_V_PASGT(V_Simc_vest_pasgt_alice_lc2_60,"M81","ALICE","MG")
        DEFINE_V_PASGT(V_Simc_vest_pasgt_alice_249,"M81","ALICE","SAW")
        DEFINE_V_PASGT(V_Simc_vest_pasgt_nade,"M81","None","Grenadier")
        DEFINE_V_PASGT(V_Simc_vest_pasgt_nade_lc2,"M81","ALICE","Grenadier")
        DEFINE_V_PASGT(V_Simc_vest_pasgt_lbv_1,"M81","LBV","Rifleman")
        DEFINE_V_PASGT(V_Simc_vest_pasgt_lbv_2,"M81","LBV","Rifleman (Alt)")
        DEFINE_V_PASGT(V_Simc_vest_pasgt_lbv_belt_1,"M81","LBV","Rifleman")
        DEFINE_V_PASGT(V_Simc_vest_pasgt_lbv_belt_2,"M81","LBV","Rifleman (Alt)")
        DEFINE_V_PASGT(V_Simc_vest_pasgt_lbv_belt_45_1,"M81","LBV","Sidearm")
        DEFINE_V_PASGT(V_Simc_vest_pasgt_lbv_belt_45_2,"M81","LBV","Sidearm (Alt)")
        DEFINE_V_PASGT(V_Simc_vest_pasgt_desu,"DCU-6","None","Rifleman")
        DEFINE_V_PASGT(V_Simc_vest_pasgt_desu_alice,"DCU-6","ALICE","Rifleman")
        DEFINE_V_PASGT(V_Simc_vest_pasgt_desu_alice_249,"DCU-6","ALICE","SAW")
        DEFINE_V_PASGT(V_Simc_vest_pasgt_desu_nade,"DCU-6","None","Grenadier")
        DEFINE_V_PASGT(V_Simc_vest_pasgt_desu_lbv_1,"DCU-6","LBV","Rifleman")
        DEFINE_V_PASGT(V_Simc_vest_pasgt_desu_lbv_2,"DCU-6","LBV","Rifleman (Alt)")
        DEFINE_V_PASGT(V_Simc_vest_pasgt_desu_lbv_belt_1,"DCU-6","LBV","Rifleman")
        DEFINE_V_PASGT(V_Simc_vest_pasgt_desu_lbv_belt_mc_1,"DCU-6","LBV","Rifleman")
        DEFINE_V_PASGT(V_Simc_vest_pasgt_dcu,"DCU-3","None","Rifleman")
        DEFINE_V_PASGT(V_Simc_vest_pasgt_dcu_alice,"DCU-3","ALICE","Rifleman")
        DEFINE_V_PASGT(V_Simc_vest_pasgt_dcu_lbv_belt_1,"DCU-3","LBV","Rifleman")
        DEFINE_V_PASGT(V_Simc_vest_pasgt_grun,"Green","None","Rifleman")
        DEFINE_V_PASGT(V_Simc_vest_pasgt_grun_alice,"Green","ALICE","Rifleman")
        DEFINE_V_PASGT(V_Simc_vest_pasgt_grun_nade,"Green","ALICE","Grenadier")
        DEFINE_V_PASGT(V_Simc_vest_pasgt_grun_lbv_belt_1,"Green","LBV","Rifleman")
        DEFINE_V_PASGT(V_Simc_vest_pasgt_erdl,"ERDL","None","Rifleman")
        DEFINE_V_PASGT(V_Simc_vest_pasgt_erdl_alice,"ERDL","ALICE","Rifleman")
        DEFINE_V_PASGT(V_Simc_vest_pasgt_erdl_nade,"ERDL","ALICE","Grenadier")
        DEFINE_V_PASGT(V_Simc_vest_pasgt_mout,"T/MOUT","None","Rifleman")
        DEFINE_V_PASGT(V_Simc_vest_pasgt_mout_alice_mc,"T/MOUT","ALICE","Rifleman")
        DEFINE_V_PASGT(V_Simc_vest_pasgt_mout_lbv_belt_mc_1,"T/MOUT","LBV","Rifleman")

        // --- LBV-88 ---
        DEFINE_V_LBV88(V_Simc_LBV_88_1,"None","Rifleman")
        DEFINE_V_LBV88(V_Simc_LBV_88_2,"None","Rifleman (Alt)")
        DEFINE_V_LBV88(V_Simc_LBV_88_alice_1,"ALICE","Rifleman")
        DEFINE_V_LBV88(V_Simc_LBV_88_alice_2,"ALICE","Rifleman (Alt)")
        DEFINE_V_LBV88(V_Simc_LBV_88_alice_45_1,"ALICE","Sidearm")
        DEFINE_V_LBV88(V_Simc_LBV_88_alice_45_2,"ALICE","Sidearm (Alt)")
        DEFINE_V_LBV88(V_Simc_LBV_88_alice_mc_1,"ALICE","Rifleman")
        DEFINE_V_LBV88(V_Simc_LBV_88_alice_mc_2,"ALICE","Rifleman (Alt)")
        DEFINE_V_LBV88(V_Simc_LBV_88_alice_45_mc_1,"ALICE","Sidearm")
        DEFINE_V_LBV88(V_Simc_LBV_88_alice_45_mc_2,"ALICE","Sidearm (Alt)")
        
        // --- RBA ---
        DEFINE_V_RBA(V_Simc_vest_RBA_mk1,"None","Rifleman")
        DEFINE_V_RBA(V_Simc_vest_rba_mk1_alice_1,"ALICE","Rifleman")
        DEFINE_V_RBA(V_Simc_vest_rba_mk1_alice_2,"ALICE","Rifleman (Alt)")
        DEFINE_V_RBA(V_Simc_vest_rba_mk1_alice_45_1,"ALICE","Sidearm")
        DEFINE_V_RBA(V_Simc_vest_rba_mk1_alice_45_2,"ALICE","Sidearm (Alt)")
        DEFINE_V_RBA(V_Simc_vest_rba_mk1_alice_nade,"ALICE","Grenadier")
        DEFINE_V_RBA(V_Simc_vest_rba_mk1_alice_249,"ALICE","SAW")
        DEFINE_V_RBA(V_Simc_vest_rba_mk1_LBV,"LBV","Rifleman")
        DEFINE_V_RBA(V_Simc_vest_rba_mk1_LBV_belt_1,"LBV","Rifleman")
        DEFINE_V_RBA(V_Simc_vest_rba_mk1_LBV_belt_2,"LBV","Rifleman (Alt)")
        DEFINE_V_RBA(V_Simc_vest_rba_mk1_LBV_belt_45_1,"LBV","Sidearm")
        DEFINE_V_RBA(V_Simc_vest_rba_mk1_LBV_belt_45_2,"LBV","Sidearm (Alt)")
        
        // --- FAUF/AWS ---
        DEFINE_V_FAUF(V_Simc_vest_fauf,"None","Rifleman")
        DEFINE_V_FAUF(V_Simc_vest_fauf_2,"None","Light")
        DEFINE_V_FAUF(V_Simc_vest_fauf_alice,"ALICE","Rifleman")
        DEFINE_V_FAUF(V_Simc_vest_fauf_alice_45,"ALICE","Sidearm")
        DEFINE_V_FAUF(V_Simc_vest_fauf_alice_249,"ALICE","SAW")
        DEFINE_V_FAUF(V_Simc_vest_fauf_LBV,"LBV","Rifleman")
        DEFINE_V_FAUF(V_Simc_vest_fauf_LBV_2,"LBV","Rifleman (Alt)")
        DEFINE_V_FAUF(V_Simc_vest_fauf_LBV_belt,"LBV","Rifleman")
        DEFINE_V_FAUF(V_Simc_vest_fauf_LBV_belt_45,"LBV","Sidearm")
        DEFINE_V_AWS(V_Simc_vest_fauf_rig_1,"FAUF","Rifleman")
        DEFINE_V_AWS(V_Simc_vest_fauf_rig_2,"FAUF","Light")
        DEFINE_V_AWS(V_Simc_vest_fauf_rig_3,"FAUF","Rifleman (Alt)")
        DEFINE_V_AWS(V_Simc_vest_fauf_rig_4,"FAUF","Light (Alt)")
        DEFINE_V_AWS(V_Simc_vest_aws_rig_1,"None","Rifleman")
        DEFINE_V_AWS(V_Simc_vest_aws_rig_2,"None","Rifleman (Alt)")
        DEFINE_V_AWS(V_Simc_vest_aws_rig_3,"None","Light")
        DEFINE_V_AWS(V_Simc_vest_aws_rig_4,"None","Light (Alt)")

        // ===================================================================================================================================
        // HEADGEAR
        // ===================================================================================================================================

        // --- M1 Helmet ---
        DEFINE_H_M1(H_Simc_M1_m81_cl,"M81","None","None","None")
        DEFINE_H_M1(H_Simc_M1_m81_ns,"M81 Alt","None","None","None")
        DEFINE_H_M1(H_Simc_M1_m81_B,"M81","Elastic","None","None")
        DEFINE_H_M1(H_Simc_M1_m81_ns_B,"M81 Alt","Elastic","None","None")
        DEFINE_H_M1(H_Simc_M1_m81_SWDG_B,"M81","Elastic","SWDG","None")
        DEFINE_H_M1(H_Simc_M1_m81_pfc,"M81","Elastic","None","PFC")
        DEFINE_H_M1(H_Simc_M1_m81_CPL,"M81 Alt","Elastic","None","CPL")
        DEFINE_H_M1(H_Simc_M1_m81_SPC,"M81","Elastic","None","SPC")
        DEFINE_H_M1(H_Simc_M1_m81_SGT,"M81 Alt","Elastic","None","SGT")
        DEFINE_H_M1(H_Simc_M1_m81_SSG,"M81","Elastic","None","SSG")
        DEFINE_H_M1(H_Simc_M1_m81_SFC,"M81 Alt","Elastic","None","SFC")
        DEFINE_H_M1(H_Simc_M1_m81_1SG,"M81","Elastic","None","1SG")
        DEFINE_H_M1(H_Simc_M1_m81_2LT,"M81 Alt","Elastic","None","2LT")
        DEFINE_H_M1(H_Simc_M1_m81_1LT,"M81","Elastic","None","1LT")
        DEFINE_H_M1(H_Simc_M1_m81_CPT,"M81 Alt","Elastic","None","CPT")
        DEFINE_H_M1(H_Simc_M1_m81_MAJ,"M81","Elastic","None","MAJ")
        DEFINE_H_M1(H_Simc_M1_m81_LTC,"M81 Alt","Elastic","None","LTC")
        DEFINE_H_M1(H_Simc_M1_m81_COL,"M81","Elastic","None","COL")
        DEFINE_H_M1(H_Simc_M1_erdl2_cl,"ERDL","None","None","None")
        DEFINE_H_M1(H_Simc_M1_erdl_B,"ERDL","Elastic","None","None")
        DEFINE_H_M1(H_Simc_M1_erdl_SGT,"ERDL","Elastic","None","SGT")
        DEFINE_H_M1(H_Simc_M1_desu_cl,"Desert","None","None","None")
        DEFINE_H_M1(H_Simc_M1_desu_B,"Desert","Elastic","None","None")
        DEFINE_H_M1(H_Simc_M1_desu_SWDG_B,"Desert","Elastic","SWDG","None")
        DEFINE_H_M1(H_Simc_M1_desu_pfc,"Desert","Elastic","None","PFC")
        DEFINE_H_M1(H_Simc_M1_desu_CPL,"Desert","Elastic","None","CPL")
        DEFINE_H_M1(H_Simc_M1_desu_SGT,"Desert","Elastic","None","SGT")

        // --- PASGT ---
        DEFINE_H_PASGT(H_Simc_pasgt_m81,"M81","None","None","None","No")
        DEFINE_H_PASGT(H_Simc_pasgt_m81_b,"M81","Standard","None","None","No")
        DEFINE_H_PASGT(H_Simc_pasgt_m81_SWDG,"M81","None","None","Down","No")
        DEFINE_H_PASGT(H_Simc_pasgt_m81_b_SWDG,"M81","Standard","None","Down","No")
        DEFINE_H_PASGT(H_Simc_pasgt_m81_SWDG_low,"M81","None","None","Up","No")
        DEFINE_H_PASGT(H_Simc_pasgt_m81_SWDG_low_b,"M81","Standard","None","Up","No")
        DEFINE_H_PASGT(H_Simc_pasgt_m81_scrim,"M81","None","Standard","None","No")
        DEFINE_H_PASGT(H_Simc_pasgt_m81_scrim_alt,"M81","None","Standard","None","No")
        DEFINE_H_PASGT(H_Simc_pasgt_m81_scrim_SWDG,"M81","None","Standard","Down","No")
        DEFINE_H_PASGT(H_Simc_pasgt_m81_scrim_panama,"M81","None","Panama","None","No")
        DEFINE_H_PASGT(H_Simc_pasgt_m81_nvo,"M81","None","None","None","Yes")
        DEFINE_H_PASGT(H_Simc_pasgt_m81_nvo_strap,"M81","None","None","None","Strap")
        DEFINE_H_PASGT(H_Simc_pasgt_desu,"DCU-6","None","None","None","No")
        DEFINE_H_PASGT(H_Simc_pasgt_desu_b,"DCU-6","Standard","None","None","No")
        DEFINE_H_PASGT(H_Simc_pasgt_desu_SWDG,"DCU-6","None","None","Down","No")
        DEFINE_H_PASGT(H_Simc_pasgt_desu_SWDG_low,"DCU-6","None","None","Up","No")
        DEFINE_H_PASGT(H_Simc_pasgt_desu_scrim,"DCU-6","None","Standard","None","No")
        DEFINE_H_PASGT(H_Simc_pasgt_desu_nvo,"DCU-6","None","None","None","Yes")
        DEFINE_H_PASGT(H_Simc_pasgt_dcu,"DCU-3","None","None","None","No")
        DEFINE_H_PASGT(H_Simc_pasgt_dcu_b,"DCU-3","Standard","None","None","No")
        DEFINE_H_PASGT(H_Simc_pasgt_dcu_SWDG,"DCU-3","None","None","Down","No")
        DEFINE_H_PASGT(H_Simc_pasgt_dcu_nvo,"DCU-3","None","None","None","Yes")
        DEFINE_H_PASGT(H_Simc_pasgt_grun,"Green","None","None","None","No")
        DEFINE_H_PASGT(H_Simc_pasgt_mout,"T/MOUT","None","None","None","No")
        
        // --- Pro-Tec ---
        DEFINE_H_PROTEC(H_Simc_protec_full,"Full","No","No","No","None")
        DEFINE_H_PROTEC(H_Simc_protec_full_swdg,"Full","No","No","No","Down")
        DEFINE_H_PROTEC(H_Simc_protec_full_swdg_low,"Full","No","No","No","Up")
        DEFINE_H_PROTEC(H_Simc_protec_full_nvo,"Full","Yes","Yes","No","None")
        DEFINE_H_PROTEC(H_Simc_protec_full_nvo_swdg,"Full","Yes","Yes","No","Down")
        DEFINE_H_PROTEC(H_Simc_protec_full_nvo_swdg_low,"Full","Yes","Yes","No","Up")
        DEFINE_H_PROTEC(H_Simc_protec_full_nvo_ir,"Full","Yes","Yes","Yes","None")
        DEFINE_H_PROTEC(H_Simc_protec_full_nvo_ir_swdg,"Full","Yes","Yes","Yes","Down")
        DEFINE_H_PROTEC(H_Simc_protec_full_nvo_ir_swdg_low,"Full","Yes","Yes","Yes","Up")
        DEFINE_H_PROTEC(H_Simc_protec_half,"Half-Cut","No","No","No","None")
        DEFINE_H_PROTEC(H_Simc_protec_half_swdg,"Half-Cut","No","No","No","Down")
        DEFINE_H_PROTEC(H_Simc_protec_half_swdg_low,"Half-Cut","No","No","No","Up")
        DEFINE_H_PROTEC(H_Simc_protec_half_nvo,"Half-Cut","Yes","No","No","None")
        DEFINE_H_PROTEC(H_Simc_protec_half_nvo_swdg,"Half-Cut","Yes","No","No","Down")
        DEFINE_H_PROTEC(H_Simc_protec_half_nvo_swdg_low,"Half-Cut","Yes","No","No","Up")
        DEFINE_H_PROTEC(H_Simc_protec_half_nvo_ir,"Half-Cut","Yes","No","Yes","None")
        DEFINE_H_PROTEC(H_Simc_protec_half_nvo_ir_swdg,"Half-Cut","Yes","No","Yes","Down")
        DEFINE_H_PROTEC(H_Simc_protec_half_nvo_ir_swdg_low,"Half-Cut","Yes","No","Yes","Up")
        DEFINE_H_PROTEC(H_Simc_protec_hs_nvo,"Half-Cut","Yes","Yes","No","None")
        DEFINE_H_PROTEC(H_Simc_protec_hs_nvo_swdg,"Half-Cut","Yes","Yes","No","Down")
        DEFINE_H_PROTEC(H_Simc_protec_hs_nvo_swdg_low,"Half-Cut","Yes","Yes","No","Up")
        DEFINE_H_PROTEC(H_Simc_protec_hs_nvo_ir,"Half-Cut","Yes","Yes","Yes","None")
        DEFINE_H_PROTEC(H_Simc_protec_hs_nvo_ir_swdg,"Half-Cut","Yes","Yes","Yes","Down")
        DEFINE_H_PROTEC(H_Simc_protec_hs_nvo_ir_swdg_low,"Half-Cut","Yes","Yes","Yes","Up")
        
        // --- CVC Helmet ---
        DEFINE_H_CVC(H_Simc_CVC,"None")
        DEFINE_H_CVC(H_Simc_CVC_G,"Down")
        DEFINE_H_CVC(H_Simc_CVC_G_low,"Up")

        // --- Boonie Hats ---
        DEFINE_H_BOONIE(H_Simc_Boon_m81_1,"M81","Standard")
        DEFINE_H_BOONIE(H_Simc_Boon_m81_2,"M81","Folded Sides")
        DEFINE_H_BOONIE(H_Simc_Boon_m81_3,"M81","Folded Back")
        DEFINE_H_BOONIE(H_Simc_Boon_m81_4,"M81","Short Brim")
        DEFINE_H_BOONIE(H_Simc_Boon_desu_1,"Desert","Standard")
        DEFINE_H_BOONIE(H_Simc_Boon_desu_2,"Desert","Folded Sides")
        DEFINE_H_BOONIE(H_Simc_Boon_desu_3,"Desert","Folded Back")
        DEFINE_H_BOONIE(H_Simc_Boon_desu_4,"Desert","Short Brim")
        DEFINE_H_BOONIE(H_Simc_Boon_dcu_1,"DCU-3","Standard")
        DEFINE_H_BOONIE(H_Simc_Boon_dcu_2,"DCU-3","Folded Sides")
        DEFINE_H_BOONIE(H_Simc_Boon_dcu_3,"DCU-3","Folded Back")
        DEFINE_H_BOONIE(H_Simc_Boon_dcu_4,"DCU-3","Short Brim")

        // --- Patrol Caps ---
        DEFINE_H_PATROL(H_Simc_Hat_Patrol_m81,"M81")
        DEFINE_H_PATROL(H_Simc_Hat_Patrol_desu,"Desert")
        DEFINE_H_PATROL(H_Simc_Hat_Patrol_dcu,"DCU-3")
        DEFINE_H_PATROL(H_Simc_Hat_MC_m81,"M81")
        DEFINE_H_PATROL(H_Simc_Hat_MC_m81_desu,"Desert")
        DEFINE_H_PATROL(H_Simc_Hat_MC_m81_dcu,"DCU-3")
    };

    class CfgVehicles
    {
        // ===================================================================================================================================
        // BACKPACKS
        // ===================================================================================================================================
        DEFINE_B_ALICE(B_simc_pack_alice_0,"OD","No","Standard","No")
        DEFINE_B_ALICE(B_simc_pack_alice_1,"OD","No","Standard","No")
        DEFINE_B_ALICE(B_simc_pack_alice_2,"OD","No","Standard","No")
        DEFINE_B_ALICE(B_simc_pack_alice_3,"OD","No","Standard","No")
        DEFINE_B_ALICE(B_simc_pack_alice_frame_1,"OD","Yes","Standard","No")
        DEFINE_B_ALICE(B_simc_pack_alice_frame_2,"OD","Yes","Standard","No")
        DEFINE_B_ALICE(B_simc_pack_alice_frame_rajio,"OD","Yes","Radio","No")
        DEFINE_B_ALICE(B_simc_pack_alice_kobel_m81,"M81 Cover","No","Standard","No")
        DEFINE_B_ALICE(B_simc_pack_alice_kobel_desu,"Desert Cover","No","Standard","No")
        DEFINE_B_ALICE(B_simc_pack_alice_kobel_dcu,"DCU Cover","No","Standard","No")
        DEFINE_B_ALICE(B_simc_pack_alice_flak_0,"OD","No","Standard","Yes")
        DEFINE_B_ALICE(B_simc_pack_alice_flak_1,"OD","No","Standard","Yes")
        DEFINE_B_ALICE(B_simc_pack_alice_flak_2,"OD","No","Standard","Yes")
        DEFINE_B_ALICE(B_simc_pack_alice_flak_3,"OD","No","Standard","Yes")
        DEFINE_B_ALICE(B_simc_pack_alice_flak_frame_1,"OD","Yes","Standard","Yes")
        DEFINE_B_ALICE(B_simc_pack_alice_flak_frame_2,"OD","Yes","Standard","Yes")
        DEFINE_B_ALICE(B_simc_pack_alice_flak_frame_rajio,"OD","Yes","Radio","Yes")
        DEFINE_B_ALICE(B_simc_pack_alice_flak_kobel_m81,"M81 Cover","No","Standard","Yes")
        DEFINE_B_ALICE(B_simc_pack_alice_flak_kobel_desu,"Desert Cover","No","Standard","Yes")
        DEFINE_B_ALICE(B_simc_pack_alice_flak_kobel_dcu,"DCU Cover","No","Standard","Yes")
    };
};