name = "ace3_arsenal_extended_sns"
author = "tyen"
prefix = "aceax_compat_sns"
mainprefix = "aceax_compat_sns"

[version]
major = 1
minor = 0
patch = 0
build = 1

[hemtt.build]
pdrive = "require"

[hemtt.check]
pdrive = "ignore"